<a href="https://colab.research.google.com/github/KhoiNguyen-sudo/DataAnalystDeepLearning/blob/main/HOMEWORD_LB3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
#LB3 
#NGUỒN : Nguyễn Thái Anh, Hồ Quốc Hùng, Lê Thị Thanh Ngân

In [61]:
#Vấn đề 1: Tiến hành tải dữ liệu vào chương trình ứng dụng Python và giải quyết vấn đề 
# ―Missing header in the csv file

In [62]:
import pandas as pd
import seaborn as sns
df_patientheartrate = pd.read_csv('https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/patient_heart_rate.csv')
print(df_patientheartrate)

       1    Mickéy Mousé    56       70kgs   72   69   71    -  -.1  -.2
0    2.0     Donald Duck  34.0   154.89lbs    -    -    -   85   84   76
1    3.0      Mini Mouse  16.0         NaN    -    -    -   65   69   72
2    4.0  Scrooge McDuck   NaN       78kgs   78   79   72    -    -    -
3    5.0    Pink Panther  54.0  198.658lbs    -    -    -   69  NaN   75
4    6.0     Huey McDuck  52.0      189lbs    -    -    -   68   75   72
5    7.0    Dewey McDuck  19.0       56kgs    -    -    -   71   78   75
6    8.0      Scööpy Doo  32.0       78kgs   78   76   75    -    -    -
7    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
8    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
9    9.0     Huey McDuck  52.0      189lbs    -    -    -   68   75   72
10  10.0    Louie McDuck  12.0       45kgs    -    -    -   92   95   87
11  11.0       Henry Nam   NaN       60kgs   78   75   72    -    -    -
12  12.0     Michel Long  34.0         NaN   65   67   55    -    -    -
13  13.0      Tana Ricky   NaN         NaN    -    -    -   68   72   70
14  14.0        UniLever   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
15  15.0             NaN  52.0      180lbs    -    -    -   68   75   72

In [63]:
# thêm tên cột ( header) vào  df_patientheartrate 
ten_cot = ["ID", "Name", "Age", "Weight", "m0006", "m0612","m1218", "f006", "f0612", "f1218"] 
# Sau đó tiến hành gán  
#CT : ten biens = pd.read_csv("đường link dữ liệu",names = tencot)
df_patientheartrate = pd.read_csv('https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/patient_heart_rate.csv', names= ten_cot) 
print(df_patientheartrate)

      ID            Name   Age      Weight m0006 m0612 m1218 f006 f0612 f1218
0    1.0    Mickéy Mousé  56.0       70kgs    72    69    71    -     -     -
1    2.0     Donald Duck  34.0   154.89lbs     -     -     -   85    84    76
2    3.0      Mini Mouse  16.0         NaN     -     -     -   65    69    72
3    4.0  Scrooge McDuck   NaN       78kgs    78    79    72    -     -     -
4    5.0    Pink Panther  54.0  198.658lbs     -     -     -   69   NaN    75
5    6.0     Huey McDuck  52.0      189lbs     -     -     -   68    75    72
6    7.0    Dewey McDuck  19.0       56kgs     -     -     -   71    78    75
7    8.0      Scööpy Doo  32.0       78kgs    78    76    75    -     -     -
8    NaN             NaN   NaN         NaN   NaN   NaN   NaN  NaN   NaN   NaN
9    NaN             NaN   NaN         NaN   NaN   NaN   NaN  NaN   NaN   NaN
10   9.0     Huey McDuck  52.0      189lbs     -     -     -   68    75    72
11  10.0    Louie McDuck  12.0       45kgs     -     -     -   92    95    87
12  11.0       Henry Nam   NaN       60kgs    78    75    72    -     -     -
13  12.0     Michel Long  34.0         NaN    65    67    55    -     -     -
14  13.0      Tana Ricky   NaN         NaN     -     -     -   68    72    70
15  14.0        UniLever   NaN         NaN   NaN   NaN   NaN  NaN   NaN   NaN
16  15.0             NaN  52.0      180lbs     -     -     -   68    75    72

In [64]:
# Vấn đề 2: Xử lý vấn đề một cột lưu hỗn hợp nhiều dữ liệu, ở đây là cột ―Name‖ chứa bao 
# gồm ―Firstname‖ và ―Lastname‖, giải pháp là ta sẽ tách ra làm 2 cột

In [65]:
#CÁCH TÁCH CỘT DÙNG SPLIT 
# TÊN BIẾN [["tên cột mới thứ 1","tên cột mới thứ 2"]] = tên biên["tên cột muốn tách"].str.split(expand = True)
df_patientheartrate[['Firstname', 'Lastname']]=df_patientheartrate['Name'].str.split(expand = True)
df_patientheartrate.head(100)

      ID            Name   Age      Weight  ... f0612 f1218 Firstname Lastname
0    1.0    Mickéy Mousé  56.0       70kgs  ...     -     -    Mickéy    Mousé
1    2.0     Donald Duck  34.0   154.89lbs  ...    84    76    Donald     Duck
2    3.0      Mini Mouse  16.0         NaN  ...    69    72      Mini    Mouse
3    4.0  Scrooge McDuck   NaN       78kgs  ...     -     -   Scrooge   McDuck
4    5.0    Pink Panther  54.0  198.658lbs  ...   NaN    75      Pink  Panther
5    6.0     Huey McDuck  52.0      189lbs  ...    75    72      Huey   McDuck
6    7.0    Dewey McDuck  19.0       56kgs  ...    78    75     Dewey   McDuck
7    8.0      Scööpy Doo  32.0       78kgs  ...     -     -    Scööpy      Doo
8    NaN             NaN   NaN         NaN  ...   NaN   NaN       NaN      NaN
9    NaN             NaN   NaN         NaN  ...   NaN   NaN       NaN      NaN
10   9.0     Huey McDuck  52.0      189lbs  ...    75    72      Huey   McDuck
11  10.0    Louie McDuck  12.0       45kgs  ...    95    87     Louie   McDuck
12  11.0       Henry Nam   NaN       60kgs  ...     -     -     Henry      Nam
13  12.0     Michel Long  34.0         NaN  ...     -     -    Michel     Long
14  13.0      Tana Ricky   NaN         NaN  ...    72    70      Tana    Ricky
15  14.0        UniLever   NaN         NaN  ...   NaN   NaN  UniLever     None
16  15.0             NaN  52.0      180lbs  ...    75    72       NaN      NaN

[17 rows x 12 columns]

In [66]:
#Xóa cột Name .Dùng hàm drop
# CT: TÊN BIẾN = TÊN BIẾN.drop("TÊN CỘT MUỐN XÓA",AXIS=1) 
#AXIS: TÊN CỘT ĐÓ NẰM Ở CỘT THỨ MẤY
df_patientheartrate = df_patientheartrate.drop('Name',axis=1)
df_patientheartrate.head(100)

      ID   Age      Weight m0006 m0612  ... f006 f0612 f1218 Firstname Lastname
0    1.0  56.0       70kgs    72    69  ...    -     -     -    Mickéy    Mousé
1    2.0  34.0   154.89lbs     -     -  ...   85    84    76    Donald     Duck
2    3.0  16.0         NaN     -     -  ...   65    69    72      Mini    Mouse
3    4.0   NaN       78kgs    78    79  ...    -     -     -   Scrooge   McDuck
4    5.0  54.0  198.658lbs     -     -  ...   69   NaN    75      Pink  Panther
5    6.0  52.0      189lbs     -     -  ...   68    75    72      Huey   McDuck
6    7.0  19.0       56kgs     -     -  ...   71    78    75     Dewey   McDuck
7    8.0  32.0       78kgs    78    76  ...    -     -     -    Scööpy      Doo
8    NaN   NaN         NaN   NaN   NaN  ...  NaN   NaN   NaN       NaN      NaN
9    NaN   NaN         NaN   NaN   NaN  ...  NaN   NaN   NaN       NaN      NaN
10   9.0  52.0      189lbs     -     -  ...   68    75    72      Huey   McDuck
11  10.0  12.0       45kgs     -     -  ...   92    95    87     Louie   McDuck
12  11.0   NaN       60kgs    78    75  ...    -     -     -     Henry      Nam
13  12.0  34.0         NaN    65    67  ...    -     -     -    Michel     Long
14  13.0   NaN         NaN     -     -  ...   68    72    70      Tana    Ricky
15  14.0   NaN         NaN   NaN   NaN  ...  NaN   NaN   NaN  UniLever     None
16  15.0  52.0      180lbs     -     -  ...   68    75    72       NaN      NaN

[17 rows x 11 columns]

In [67]:
# Vấn đề 3: Cột Weight có vấn đề về không thống nhất các đơn vị đo lường trong dữ liệu. 
# Ta sẽ chuyển các đơn vị về thành đơn vị chuẩn ―kg‖

In [68]:
weight=df_patientheartrate['Weight']
for i in range(len(weight)):
  x = str(weight[i])
  if "lbs" in x[-3:]:
    #remove the lbs from the value
    x = x[:-3]
    float_x = float(x)
    y = int(float_x/2.205)
    y = str(y)+"kgs"
    weight[i] = y
print(df_patientheartrate.head(100))

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -    Scööpy      Doo
8    NaN   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN       NaN      NaN
9    NaN   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN       NaN      NaN
10   9.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [69]:
# Vấn đề 4: Vấn đề về xuất hiện dòng dữ liệu rỗng (không có giá trị: NaN). Giải pháp có 
#thể đưa ra là xóa bỏ

In [70]:
#dùng hàm dropna để xóa dữ liệu rỗng
#CT tên biến.dropna(how="all",inplace=True)
df_patientheartrate.dropna(how="all", inplace=True)
df_patientheartrate.head(100)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -    Scööpy      Doo
10   9.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [71]:
# Vấn đề 5: Có nhiều dòng dữ liệu bị trùng lắp thông tin hoàn toàn[fullname, lastname, 
# age, weight,....], giải pháp đưa ra là chỉ giữ lại một dòng dữ liệu, tuy nhiên giải pháp phải 
# dựa trên nghiệp vụ của tập dữ liệu và quan sát của người xử lý.

In [72]:
# xóa những dữ liệu trùng dùng hàm drop_duplicates 
##tên biến  =tiến biến. drop_duplicates(subset=["tên cột có chứa dữ liệu trùng lần 1","tên cột có chứa dữ liệu trùng lần 2",...])
df_patientheartrate = df_patientheartrate.drop_duplicates(subset=['Firstname','Lastname', 'Age', 'Weight'])
df_patientheartrate.head(100)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -    Scööpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [73]:
# Vấn đề 6: Xuất hiện dữ liệu bị ảnh hưởng bởi lỗi non-ASCII, không định dạng ASCII. 
# Giải pháp: Tùy vào nghiệp vụ ta có thể: xóa dữ liệu tại đó, thay thế bằng dữ liệu khác 
# hoặc thay bằng việc đánh dấu bằng một kí tự khác (ví dụ: ‗warning‘)

In [74]:
df_patientheartrate.Firstname.replace({r'[^\x00-\x7F]+':''}, regex=True,inplace=True)
df_patientheartrate.replace({r'[^\x00-\x7F]+':''}, regex=True,inplace=True)
df_patientheartrate.head(100)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4582: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4389: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -   68    72    70      Tana    Ricky
15  14.0   NaN    NaN   NaN   NaN   NaN  NaN   NaN   NaN  UniLever     None
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [75]:
# Vấn đề 7: ―Missing values‖, vấn đề này xảy ra tại các cột ―Age‖, ―Weight‖ và ―Heart 
# Rate‖. Thiếu dữ liệu (dữ liệu không đầy đủ) là vấn đề xảy ra nhiều trong các nguồn dữ 
# liệu do nhiều nguyên nhân chủ quan lẫn khách quan.Có một vài giải pháp để xử lý vấn đề 
# này, chủ yếu dựa trên kinh nghiệm và nghiệp vụ về tập dữ liệu đó. Một số giải pháp đưa 
# đề xuất từ chuyên gia như sau: 
# a. Deletion: Remove records with missing values
# b. Dummy substitution: Replace missing values with a dummy but valid value: e.g.: 0 for numerical values.
# c. Mean substitution: Replace the missing values with the mean.
# d. Frequent substitution: Replace the missing values with the most frequent item.
# e. Improve the data collector: Your business folk will talk to the clients and inform them about why it is worth fixing the problem with the data collector.
# Yêu cầu:
# Thống kê thông tin dữ liệu thiếu trên từng biến Age và Weight
# Yêu cầu xử lý dữ liệu thiếu như sau: Nếu dòng nào có Age hoặc Weight có dữ liệu thì phần Age hoặc Weight được tính như bên dưới, nếu thiếu cả 2 thông tin thì xóa dòng o Age: Giá trị thay thế là mean của các giá trị trong cột Age o Weight: Giá trị thay thế là mean của các giá trị trong cột Weight theo nhóm giới tính

In [78]:
index_ageweightnull = df_patientheartrate[df_patientheartrate['Age'].isna() & df_patientheartrate['Weight'].isna()].index
index_ageweightnull

Int64Index([14, 15], dtype='int64')

In [79]:
df_patientheartrate.drop(index_ageweightnull, inplace=True)
df_patientheartrate.head(100)

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [80]:
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
sns.heatmap(df_patientheartrate.isna(), 
            yticklabels=False, 
            cbar=True, 
            cmap='viridis')

In [81]:
df_patientheartrate['Age'].fillna(df_patientheartrate['Age'].mean(), inplace =False)

0     56.0
1     34.0
2     16.0
3     36.1
4     54.0
5     52.0
6     19.0
7     32.0
11    12.0
12    36.1
13    34.0
16    52.0
Name: Age, dtype: float64

In [ ]:
#Vấn đề 8
#"một cột chứa quá nhiều thông tin cần được phân rã", như trong bài toán này ta thấy header "m0006" chứa các nội dung bao gồm: m -> male, 1218 ~ 12-18 (mm-dd). Còn giá trị thì là kết quả huyết áp

In [82]:
df_patientheartrate

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
16  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [83]:
df = pd.melt(df_patientheartrate, id_vars=['ID', 'Age', 'Weight', 'Firstname', 'Lastname'], value_name="PulseRate",var_name="sex_and_time").sort_values(['ID', 'Age', 'Weight', 'Firstname', 'Lastname']) 
df

      ID   Age Weight Firstname Lastname sex_and_time PulseRate
0    1.0  56.0  70kgs     Micky     Mous        m0006        72
12   1.0  56.0  70kgs     Micky     Mous        m0612        69
24   1.0  56.0  70kgs     Micky     Mous        m1218        71
36   1.0  56.0  70kgs     Micky     Mous         f006         -
48   1.0  56.0  70kgs     Micky     Mous        f0612         -
..   ...   ...    ...       ...      ...          ...       ...
23  15.0  52.0  81kgs       NaN      NaN        m0612         -
35  15.0  52.0  81kgs       NaN      NaN        m1218         -
47  15.0  52.0  81kgs       NaN      NaN         f006        68
59  15.0  52.0  81kgs       NaN      NaN        f0612        75
71  15.0  52.0  81kgs       NaN      NaN        f1218        72

[72 rows x 7 columns]

In [85]:
#Extract sex, hour lower bound and hour upper dound group
tmp_df= df["sex_and_time"].str.extract("(\D)(\d+)(\d{2})", expand=True) 
tmp_df.head(100)

    0   1   2
0   m  00  06
12  m  06  12
24  m  12  18
36  f   0  06
48  f  06  12
.. ..  ..  ..
23  m  06  12
35  m  12  18
47  f   0  06
59  f  06  12
71  f  12  18

[72 rows x 3 columns]

In [89]:
#Name columns
tmp_df.columns=["Sex","hours_lower","hours_upper"] 
tmp_df.head(100)

   Sex hours_lower hours_upper
0    m          00          06
12   m          06          12
24   m          12          18
36   f           0          06
48   f          06          12
..  ..         ...         ...
23   m          06          12
35   m          12          18
47   f           0          06
59   f          06          12
71   f          12          18

[72 rows x 3 columns]

In [90]:
#Create Time column based on "hours_lower" and "hours_upper" columns
tmp_df["Time"]=tmp_df["hours_lower"] + "-"+ tmp_df["hours_upper"]

tmp_df.head(5)

   Sex hours_lower hours_upper   Time
0    m          00          06  00-06
12   m          06          12  06-12
24   m          12          18  12-18
36   f           0          06   0-06
48   f          06          12  06-12

In [91]:
#Merge
df =pd.concat([df, tmp_df], axis=1) 
df.head(100)

      ID   Age Weight Firstname  ... Sex hours_lower hours_upper   Time
0    1.0  56.0  70kgs     Micky  ...   m          00          06  00-06
12   1.0  56.0  70kgs     Micky  ...   m          06          12  06-12
24   1.0  56.0  70kgs     Micky  ...   m          12          18  12-18
36   1.0  56.0  70kgs     Micky  ...   f           0          06   0-06
48   1.0  56.0  70kgs     Micky  ...   f          06          12  06-12
..   ...   ...    ...       ...  ...  ..         ...         ...    ...
23  15.0  52.0  81kgs       NaN  ...   m          06          12  06-12
35  15.0  52.0  81kgs       NaN  ...   m          12          18  12-18
47  15.0  52.0  81kgs       NaN  ...   f           0          06   0-06
59  15.0  52.0  81kgs       NaN  ...   f          06          12  06-12
71  15.0  52.0  81kgs       NaN  ...   f          12          18  12-18

[72 rows x 11 columns]

In [100]:
df.head(5)

     ID   Age Weight Firstname Lastname PulseRate Sex   Time
0   1.0  56.0  70kgs     Micky     Mous        72   m  00-06
12  1.0  56.0  70kgs     Micky     Mous        69   m  06-12
24  1.0  56.0  70kgs     Micky     Mous        71   m  12-18
36  1.0  56.0  70kgs     Micky     Mous         -   f   0-06
48  1.0  56.0  70kgs     Micky     Mous         -   f  06-12

In [ ]:
#Vấn đề 10

In [103]:
from google.colab import drive
drive.mount('/drive')

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).

In [105]:
df.to_csv('patient_heart_rate_clean.csv')